services:
  - type: web
    name: geoffe-dashboard-api
    env: python
    plan: free
    rootDir: Backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11.9
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_VERSION
        value: 23.3.1
